# Generated by Django 5.0.3 on 2024-03-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_remove_event_user_id_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
